### PR TITLE
Encode id param in a Path as a URI and not as a URL

### LINKED ISSUE #10936: GET Request parameter double decoded
I've created a fresh rest-api application with a controller containing a `show` action mapped at `GET /test/$id`. When the `id` parameter contains a `+` sign it's correctly decoded as a space but if the `+` is encoded as `%2B` in the url, the param is double decoded to a space while I would expect it to be a `+`
For example, I've a controller with just:

```
class TestController {
    static responseFormats = ['json', 'xml']
    
    def show() {
        log.info "Showing ID ${params.id}"
        respond id: params.id
    }
}

```
mapped to url `/test/$id`

If I open URL `http://localhost:8080/test/1+1` the response is `{"id":"1 1"}`
If I open URL `http://localhost:8080/test/1%2B1` the response is still `{"id":"1 1"}` while I expect it to be `{"id":"1+1"}`

Also in the log and debugging the application `params.id` is equal to `1 1` and not `1+1`

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create a fresh app with profile rest-api (grails create-app param-decoding --profile=rest-api)
2. create a new controller (grails create-controller Test)
3. create a `show` action as the one above
4. invoke the show action opening the url http://localhost:8080/test/1%2B1

### Expected Behaviour
`params.id` should be `1+1`

### Actual Behaviour
`params.id` is `1 1`

### Environment Information

- **Operating System**: macOS 10.13.3
- **Grails Version:** 3.3.2
- **JDK Version:** 1.8.0_131

### Example Application
https://github.com/thagul/param-decoding

### PR DESCRIPTION
**Pull request by ilopmar**
Fixes #10936

### CODE REVIEW

File: grails-web-url-mappings/src/test/groovy/org/grails/web/mapping/mvc/EncodePathFromURISpec.groovy [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+        def handlerChain = handler.getHandler(request)
+
+        def handlerAdapter = new UrlMappingsInfoHandlerAdapter()
+        def result = handlerAdapter.handle(request, webRequest.response, handlerChain.handler)
+
+        then: 'the id parameter is not encoded as a URL'
+        webRequest.parameterMap.id == '1+1'
+
+        where:
+        uriId << ['1+1', '1%2B1']
```
Comment (jameskleeh) [inline grails-web-url-mappings/src/test/groovy/org/grails/web/mapping/mvc/EncodePathFromURISpec.groovy]: I think if the url comes in as `/book/show/1+1`, the correct value for id should be `1 1`. The second test seems correct to me. Thoughts?

Comment (ilopmar) [reply grails-web-url-mappings/src/test/groovy/org/grails/web/mapping/mvc/EncodePathFromURISpec.groovy]: Please take a look at https://github.com/grails/grails-core/issues/10936#issuecomment-365662504 because according to RFC 3986 `1+1` is part of the Path and it shouldn't be encoded as a URL but as a URI.

**Comment by davydotcom** [comment]
@puneetbehl want to revive this one.  I think it is totally valid. It seems @graemerocher may agree per the linked issue. But i can defer to him to respond.
