### PR TITLE
Make Grails property resolution consistent with Spring

### LINKED ISSUE #10670: grails config property resolution not consistent with spring
Spring boot allows overriding config by means of environment variables.  As most operating systems disallow period-separated key names, spring allows using underscores instead (e.g. `SPRING_CONFIG_NAME` instead of `spring.config.name`, environment variable name being case insensitive). This approach does not work in grails.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. add two application.yml config properties `property.with.period: from-yml` and `property_with_underscore: from-yml`
2. define two environment variables `property_with_period=from-env` and `property_with_underscore=from-env` and run the application

```
$ git clone https://github.com/acondrat/grails-example-app
$ cd grails-example-app

# First test - using lowercase environment variables
$ property_with_period=from-env property_with_underscore=from-env ./gradlew bootRun
$ curl http://localhost:8080/hello
from-yml | from-env | from-env | from-env

# Second test - using uppercase environment variables
$ PROPERTY_WITH_PERIOD=from-env PROPERTY_WITH_UNDERSCORE=from-env ./gradlew bootRun
$ curl http://localhost:8080/hello
from-yml | from-env | from-yml | from-env
```

### Expected Behaviour

Both properties should be evaluated to `from-env`

### Actual Behaviour

`grailsApplication.config.getProperty("property.with.period")` resolves to `from-yml`

### Environment Information

- **Operating System**: Linux 4.4.0-72
- **Grails Version:** 3.2.10
- **JDK Version:** 1.8.0_121

### Example Application

https://github.com/acondrat/grails-example-app

### PR DESCRIPTION
**Pull request by ilopmar**
Fixes #10670

### CODE REVIEW

File: grails-core/src/main/groovy/org/grails/config/NavigableMapConfig.java [hunk 1]
```diff
@@ -203,19 +210,33 @@ public String getProperty(String key, String defaultValue) {
...
+        if (propertySources != null) {
+            for (PropertySource<?> propertySource : propertySources) {
+                Object originalValue = propertySource.getProperty(key);
+                if (originalValue != null) {
+                    return convertValueIfNecessary(originalValue, targetType, defaultValue);
+                }
             }
-            else {
-                if(!(originalValue instanceof NavigableMap)) {
+        }
```
Comment (graemerocher) [inline grails-core/src/main/groovy/org/grails/config/NavigableMapConfig.java]: rather than iterating all the property sources which will slow down each property resolution, why not such convert the key (ie `key.toLowerCase(Locale.English).replace('_', '.')`. Wouldn't that work the same?

Comment (ilopmar) [reply grails-core/src/main/groovy/org/grails/config/NavigableMapConfig.java]: It's not only that logic. Take a look at what Spring is doing: https://github.com/spring-projects/spring-framework/blob/4.3.x/spring-core/src/main/java/org/springframework/core/env/SystemEnvironmentPropertySource.java#L104-L142

And I wanted to avoid copying-pasting all that code but if you think it's better, I can do it.

Comment (ilopmar) [reply grails-core/src/main/groovy/org/grails/config/NavigableMapConfig.java]: Sorry, now I remember the real reason why I needed to iterate all the property sources: The reason is about **priority**. 

The value for the property in `configMap` is the one defined on  `application.yml` and it's not overridden with the enviroment variables. So, if we search only in `configMap` (no matter if we replace `.`, `_`, `-`) the value returned will always be the one defined in `application.yml` and no the value defined as environment variable when running the application.

Comment (graemerocher) [reply grails-core/src/main/groovy/org/grails/config/NavigableMapConfig.java]: then you can do a check first for `System.getenv(..)` which will give you whether the environment variable is present.

Comment (ilopmar) [reply grails-core/src/main/groovy/org/grails/config/NavigableMapConfig.java]: Change done in https://github.com/grails/grails-core/pull/10937/commits/65f7bc6b82103841106a52bb9d35947d2d19662d
