### PR TITLE
Fix GrailsCompileStatic for Grails PersistentEntity with an inner-class

### LINKED ISSUE #12101: @GrailsCompileStatic fails on domain class with inner enum & mapping block
This issue is similar to #10808 but instead of the `constraints` block it is about the `mapping` block.

### Steps to Reproduce
1. Create a **domain class** that has an **inner enum** and a **mapping block** (which can even be empty).
```
@GrailsCompileStatic
class User {
    String username
    State state

    static mapping = {
        state(enumType: "string", defaultValue: State.ACTIVE)
    }

    enum State { ACTIVE, INACTIVE, UNKNOWN }
}
```

2. Build the project with `./gradlew build`.

### Expected Behaviour

Compilation succeeds.

### Actual Behaviour

Compilation fails.

Error:
```
> Task :compileGroovy
startup failed:
General error during canonicalization: Cannot get property 'initialExpression' on null object

java.lang.NullPointerException: Cannot get property 'initialExpression' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
	at org.grails.compiler.DomainMappingTypeCheckingExtension$_run_closure4.doCall(DomainMappingTypeCheckingExtension.groovy:54)
	...
```

### Environment Information

- **Operating System**: Linux
- **Grails Version:** 4.0.x
- **JDK Version:** 8

### Example Application

https://github.com/jamesdh/gorm-static-inner-enum-bug (already provided in https://github.com/grails/grails-core/issues/10808#issuecomment-655582363 by @jamesdh).

### PR DESCRIPTION
**Pull request by puneetbehl**
Fixes #12101

### CODE REVIEW

File: grails-test-suite-uber/src/test/groovy/grails/compiler/GrailsCompileStaticCompilationErrorsSpec.groovy [hunk 1]
```diff
@@ -188,6 +188,42 @@ class SomeClass implements grails.validation.Validateable {
         c
     }
 
+    @Issue('GRAILS-12101')
+    void 'Test compiling mapping with inner class'() {
+        given:
+        def gcl = new GroovyClassLoader()
+
+        when: 'a class marked with @GrailsCompileStatic invokes dynamic finders on a non-domain class inside of a method marked with TypeCheckingMode.SKIP'
```
Comment (darxriggs) [inline grails-test-suite-uber/src/test/groovy/grails/compiler/GrailsCompileStaticCompilationErrorsSpec.groovy:196]: This description on the `when` block here and in line 173 is I guess a copy & paste error from line 144 and should be removed or corrected.
